name: smart_parking_app
description: "A Flutter Project IOT team."
publish_to: 'none'

version: 1.0.0+3

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^2.15.1
  firebase_auth: ^4.7.3
  firebase_database: ^10.2.5
  firebase_storage: ^11.6.0
  google_sign_in: ^6.1.5
  lottie: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/google_logo.png
    - assets/success_animation.json
